# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Project
  displayName: Build Project
  jobs:
  - job: Project
    displayName: Project
    pool:
      name: default
    steps:
    - task: oc-cmd@2
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'Openshift Javanes'
        cmd: 'oc new-project azure-prueba'

